### ISSUE TITLE
New Culinary Arts Recipes

### ISSUE THREAD

**Issue by ClayC90** [ClayC90/ClaysToolKit#32]
In Culinary we don't just slap pieces of meat onto fire, we decorate them, we mince the meat and we throw it in a plate with pasta!

Let's add new ways to cook, whilst having it not going OP in skill point gainings

**Comment by ecoemmeck** [comment]
with the new foods could also add in normal tacos and lasagna

**Comment by ClayC90** [comment]
started as a project instead.
